<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $ship = 'Ships in 5–7 business days';
        $catId = Category::pluck('id', 'slug');

        $products = [
            ['sku' => 'QS-APP-001', 'name' => 'QS Golf Shirt — Dark Green', 'category' => 'apparel', 'price' => 580, 'orig_price' => 750, 'emoji' => '👕', 'badge' => 'Popular', 'stock' => 18, 'image' => 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => ['sizes' => ['S','M','L','XL','XXL']], 'features' => ['Moisture wicking fabric','UV protection built-in','Custom branding included',$ship], 'description' => 'Our flagship dark green golf shirt, crafted from premium moisture-wicking fabric. Ideal for corporate golf days, client gifts, and team branded events across South Africa.'],
            ['sku' => 'QS-APP-002', 'name' => 'QS Golf Shirt — White', 'category' => 'apparel', 'price' => 580, 'orig_price' => 750, 'emoji' => '👔', 'badge' => null, 'stock' => 22, 'image' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => ['sizes' => ['S','M','L','XL','XXL']], 'features' => ['Moisture wicking fabric','UV protection built-in','Custom branding included',$ship], 'description' => 'Classic white golf shirt with clean lines and premium finish. Perfect for a crisp, professional look on and off the course.'],
            ['sku' => 'QS-APP-003', 'name' => 'QS Golf Shirt — Grey', 'category' => 'apparel', 'price' => 580, 'orig_price' => 750, 'emoji' => '🧥', 'badge' => null, 'stock' => 15, 'image' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => ['sizes' => ['S','M','L','XL','XXL']], 'features' => ['Moisture wicking fabric','UV protection built-in','Custom branding included',$ship], 'description' => 'Sophisticated grey golf shirt offering a neutral, versatile base for any corporate branding. Pairs well with all team colour schemes.'],
            ['sku' => 'QS-APP-004', 'name' => 'QS Premium Golf Cap', 'category' => 'apparel', 'price' => 320, 'orig_price' => 420, 'emoji' => '🧢', 'badge' => 'Best Seller', 'stock' => 3, 'image' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['One size adjustable','Embroidered QS logo','UV protection',$ship], 'description' => 'The most popular item in our range. An adjustable, premium golf cap with embroidered QS branding — a staple for every corporate golf day kit.'],
            ['sku' => 'QS-DRK-001', 'name' => 'QS Insulated Tumbler', 'category' => 'drinkware', 'price' => 290, 'orig_price' => 380, 'emoji' => '🥤', 'badge' => 'Sale', 'stock' => 25, 'image' => 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Double-wall insulation','Keeps drinks cold 12hrs / hot 8hrs','Laser-engraved branding',$ship], 'description' => 'Premium stainless steel insulated tumbler with laser-engraved QS branding. A practical, high-perceived-value gift for any corporate event.'],
            ['sku' => 'QS-DRK-002', 'name' => 'QS Water Bottle (500ml)', 'category' => 'drinkware', 'price' => 220, 'orig_price' => 280, 'emoji' => '💧', 'badge' => null, 'stock' => 30, 'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['BPA-free 500ml bottle','Leak-proof lid','Screen-printed branding',$ship], 'description' => 'Lightweight 500ml water bottle, perfect for the course. BPA-free with a secure leak-proof lid and prominent QS screen print.'],
            ['sku' => 'QS-GLF-001', 'name' => 'QS Branded Golf Balls (3-pack)', 'category' => 'golf-accessories', 'price' => 380, 'orig_price' => 480, 'emoji' => '⛳', 'badge' => 'New', 'stock' => 40, 'image' => 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Pack of 3 premium golf balls','Custom QS logo print','Tournament quality',$ship], 'description' => 'Three tournament-quality golf balls with custom QS logo printing. A classic inclusion in any corporate golf day goodie bag.'],
            ['sku' => 'QS-GLF-002', 'name' => 'QS Branded Golf Balls (6-pack)', 'category' => 'golf-accessories', 'price' => 720, 'orig_price' => 880, 'emoji' => '⛳', 'badge' => null, 'stock' => 35, 'image' => 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Pack of 6 premium golf balls','Custom QS logo print','Tournament quality',$ship], 'description' => 'Six tournament-quality golf balls in a branded sleeve. Ideal for Standard and Premium corporate packages or as a standalone client gift.'],
            ['sku' => 'QS-GLF-003', 'name' => 'QS Premium Golf Towel', 'category' => 'golf-accessories', 'price' => 180, 'orig_price' => 240, 'emoji' => '🏌️', 'badge' => null, 'stock' => 28, 'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Microfibre construction','Clip attachment for bag','Embroidered QS branding',$ship], 'description' => 'Plush microfibre golf towel with a sturdy bag-clip attachment. Embroidered QS logo adds a premium finish to this everyday course essential.'],
            ['sku' => 'QS-GLF-004', 'name' => 'QS Golf Shoe Bag', 'category' => 'golf-accessories', 'price' => 160, 'orig_price' => 210, 'emoji' => '👜', 'badge' => null, 'stock' => 20, 'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => ['colours' => ['Dark Green','White']], 'features' => ['Breathable mesh construction','QS logo print','Available in green or white',$ship], 'description' => 'A practical, well-made shoe bag in breathable mesh fabric. Available in dark green and white to match any team colour scheme.'],
            ['sku' => 'QS-GLF-005', 'name' => 'QS Golf Umbrella', 'category' => 'golf-accessories', 'price' => 480, 'orig_price' => 620, 'emoji' => '☂️', 'badge' => null, 'stock' => 5, 'image' => 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Extra-large 68" canopy','Fibreglass wind-resistant frame','QS branding on panels',$ship], 'description' => 'A large, wind-resistant golf umbrella with QS branding across the canopy. A premium gift that ensures your brand is visible in all conditions.'],
            ['sku' => 'QS-GFT-001', 'name' => 'QS Premium Gift Box', 'category' => 'gift-sets', 'price' => 950, 'orig_price' => 1200, 'emoji' => '🎁', 'badge' => 'Top Pick', 'stock' => 12, 'image' => 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['Golf balls (3-pack)','Golf towel','Tee set','Premium branded box',$ship], 'description' => 'A beautifully presented gift box containing QS branded golf balls, a premium towel, and a tee set — packaged in a premium branded box. Perfect client gift.'],
            ['sku' => 'QS-GFT-002', 'name' => 'QS Corporate Starter Pack', 'category' => 'gift-sets', 'price' => 1650, 'orig_price' => 2100, 'emoji' => '🏆', 'badge' => 'Corporate', 'stock' => 8, 'image' => 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => ['sizes' => ['S','M','L','XL','XXL']], 'features' => ['Golf shirt (your size)','Golf cap','Golf balls (3-pack)','Tumbler','Premium branded packaging',$ship], 'description' => 'The complete starter pack — shirt, cap, branded balls, and a tumbler all in one premium package. The go-to choice for impressing clients and rewarding staff.'],
            ['sku' => 'QS-STN-001', 'name' => 'QS Notebook & Pen Set', 'category' => 'stationery', 'price' => 140, 'orig_price' => 190, 'emoji' => '📓', 'badge' => null, 'stock' => 45, 'image' => 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&h=600&fit=crop&auto=format&q=80', 'variants' => null, 'features' => ['A5 hardcover notebook','Matching branded pen','QS logo on cover',$ship], 'description' => 'An A5 hardcover notebook and matching pen, both bearing QS branding. A stylish, practical addition to any corporate golf day package.'],
        ];

        foreach ($products as $i => $p) {
            $slug = $p['category'];
            unset($p['category']);
            $p['category_id'] = $catId[$slug];
            $p['sort_order'] = $i + 1;
            Product::updateOrCreate(['sku' => $p['sku']], $p);
        }
    }
}
